CREATE TABLE client (
  client_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  gender VARCHAR(20) NOT NULL,
  age INT NOT NULL,
  identification VARCHAR(20) NOT NULL UNIQUE,
  address VARCHAR(255) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  password VARCHAR(100) NOT NULL,
  status BOOLEAN NOT NULL
);

CREATE TABLE account (
  account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_number VARCHAR(30) NOT NULL UNIQUE,
  account_type VARCHAR(20) NOT NULL,
  initial_balance DECIMAL(19,2) NOT NULL,
  status BOOLEAN NOT NULL,
  client_id BIGINT NOT NULL,
  CONSTRAINT fk_account_client FOREIGN KEY (client_id) REFERENCES client(client_id)
);

CREATE TABLE movement (
  movement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movement_date TIMESTAMP NOT NULL,
  movement_type VARCHAR(20) NOT NULL,
  amount DECIMAL(19,2) NOT NULL,
  balance DECIMAL(19,2) NOT NULL,
  account_id BIGINT NOT NULL,
  CONSTRAINT fk_movement_account FOREIGN KEY (account_id) REFERENCES account(account_id)
);

CREATE INDEX idx_account_client ON account(client_id);
CREATE INDEX idx_movement_account_date ON movement(account_id, movement_date);

ALTER TABLE client
ADD CONSTRAINT uk_client_identification UNIQUE (identification);
